### ISSUE TITLE
java.lang.Throwable: 'this constructor' is deprecated and going to be removed soon. 

### ISSUE THREAD

**Issue by Karim-53** [meanmail/PyAnnotations#3]
**Describe the bug**
doesn't look to work on pycharm

**To Reproduce**
nothing special just installed

**Screenshots**

```
Following exceptions happened soon after this one, most probably they are induced.


2022-12-23T06:53:50.564
java.lang.Throwable: 'this constructor' is deprecated and going to be removed soon. 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:105)
	at com.jetbrains.python.inspections.PyInspectionVisitor.<init>(PyInspectionVisitor.java:52)
	at ru.meanmail.codeInspection.BaseInspectionVisitor.<init>(BaseInspectionVisitor.kt:12)
	at ru.meanmail.codeInspection.UnionWithOneChildToChildInspection$Companion$Visitor.<init>(UnionWithOneChildToChildInspection.kt:26)
	at ru.meanmail.codeInspection.UnionWithOneChildToChildInspection.buildVisitor(UnionWithOneChildToChildInspection.kt:21)
	at com.intellij.codeInspection.InspectionEngine.createVisitor(InspectionEngine.java:66)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.createContext(InspectionRunner.java:358)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:119)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:117)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```
**IDE (please complete the following information. See Main Menu -> Help -> About):**

 - OS: Windows 10
 - Product: PyCharm Pro
- Build #PY-223.7571.203, built on November 30, 2022
- Runtime version: 17.0.5+1-b653.14 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version2022.1

**Additional context**

**Comment by meanmail** [comment]
Fixed
